# Generated by Django 5.2 on 2025-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CartItems",
            fields=[
                (
                    "cart_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "cart_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Carts",
            fields=[
                ("cart_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("total_qty", models.IntegerField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "db_table": "carts",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("category_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "categories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Clerks",
            fields=[
                ("clerk_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "clerks",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Colors",
            fields=[
                ("color_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("color_name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "colors",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerAddresses",
            fields=[
                ("address_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "street_address",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=250, null=True)),
                ("state", models.CharField(blank=True, max_length=250, null=True)),
                ("country", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
            ],
            options={
                "db_table": "customer_addresses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("customer_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=250)),
                ("phone", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "db_table": "customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Deliveries",
            fields=[
                ("delivery_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("delivery_address", models.CharField(max_length=255)),
                ("delivery_method", models.TextField()),
                ("delivery_status", models.TextField(blank=True, null=True)),
                (
                    "scheduled_delievery_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("actual_dt", models.DateTimeField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "deliveries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Drivers",
            fields=[
                ("driver_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("driver_license", models.CharField(max_length=50, unique=True)),
                ("license_country", models.CharField(max_length=200)),
                ("vehicle_type", models.TextField()),
                (
                    "plate_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("num_of_deliveries", models.IntegerField(blank=True, null=True)),
                (
                    "profile_pic",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "drivers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("employee_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=200, unique=True)),
                ("birthday", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "employees",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "inventory_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "inventory",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                (
                    "order_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                "db_table": "order_items",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                ("order_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order_date", models.DateTimeField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "permission_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("permission_name", models.CharField(max_length=50)),
                ("level_number", models.IntegerField()),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                ("image_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=500)),
                ("is_main", models.BooleanField(default=False)),
                ("alt_text", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "product_images",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("product_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "prod_reviews",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                ("featured", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "products",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                ("role_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(max_length=50, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sellers",
            fields=[
                ("seller_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("phone", models.CharField(max_length=200, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("sex", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sellers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SellersAddresses",
            fields=[
                (
                    "seller_add_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("street_address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "sellers_addresses",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stores",
            fields=[
                ("store_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("store_name", models.CharField(max_length=100, unique=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                ("store_logo", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "payment_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "website_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reviews", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "stores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SubCategories",
            fields=[
                (
                    "subcategory_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("subcategory_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "subcategories",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Verifications",
            fields=[
                (
                    "verification_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("government_id", models.CharField(max_length=200, unique=True)),
                ("country_issued_id", models.CharField(max_length=200)),
                ("business_name", models.CharField(max_length=200, unique=True)),
                ("business_regis_num", models.CharField(max_length=200, unique=True)),
                ("bank_name", models.CharField(max_length=200)),
                ("bank_account_number", models.CharField(max_length=100, unique=True)),
                ("routing_number", models.CharField(max_length=100)),
                ("status", models.TextField(blank=True, null=True)),
                ("decision_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "verifications",
                "managed": False,
            },
        ),
    ]
