# Generated by Django 5.2 on 2025-06-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReviews",
            fields=[
                ("review_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_reviews",
                "managed": False,
            },
        ),
    ]
