# Generated by Django 5.2 on 2025-06-20 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_productreviews"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customers",
            options={"managed": False, "verbose_name_plural": "Customers"},
        ),
    ]
