# Generated by Django 5.2 on 2025-08-26 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_webhookeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSessionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.orders')),
            ],
            options={
                'db_table': 'order_session_map',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stripe_sessions', to='core.orders')),
            ],
            options={
                'db_table': 'stripe_checkout_sessions',
                'managed': True,
            },
        ),
    ]
