# Generated by Django 5.2 on 2025-09-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ordersessionmap_stripecheckoutsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeCheckoutSession',
        ),
    ]
